### PR TITLE
Allow text renderer

### PR DESCRIPTION
**Pull request by Errorname**
Having a text renderer can help to add more functionnalities (issue #61)

### CODE REVIEW

**Comment by rexxars** [comment]
This looks great! Could you add some tests to ensure it doesn't break the default text renderer, and that future changes won't break custom text renderer support?

**Comment by Errorname** [comment]
I'm not sure I did the tests right (first time using jest), don't hesitate to tell me what I can do better!

**Comment by sebabouche** [comment]
Is there a chance to see this PR merged over the weekend :smiley: ?

**Comment by sebabouche** [comment]
I'll do a PR on the readme to add an example on how to user it with [emoji-mart](https://github.com/missive/emoji-mart/).

**Comment by rexxars** [comment]
Released as 3.2.0, thanks a bunch!

**Pull request merged**
